layout_spectrum: 1
typography_spectrum: 0.3163265
color:
  saturation: 0.9830576
  lightness: 0.3413822
  brandStrength: 0.8694951
  brandColors:
    - '#333333'
    - '#FFFFFF'
    - '#9D3A94'
    - '#6E6E6E'
    - '#B5B5B5'
  rhythmicContrast: 0.9137009
name: JEllison Images
